# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

######################################
    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        
######################################
    - name: Configure CMake
      shell: bash
      run: |
        cmake -B "${{ steps.strings.outputs.build-output-dir }}" \
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DPATCH_VERSION=${{ github.run_number }} \
          -S "${{ github.workspace }}"

######################################
    - name: Build
      run: cmake --build "${{ steps.strings.outputs.build-output-dir }}" --config ${{ matrix.build_type }}



######################################
#    - name: Test
#      working-directory: ${{ steps.strings.outputs.build-output-dir }}
#      run: ctest --output-on-failure -C ${{ matrix.build_type }}

######################################

    - name: Install NSIS (Windows only)
      if: ${{ matrix.os == 'windows-latest' }}
      run: choco install nsis --no-progress -y

    - name: Package
      run: cmake --build "${{ steps.strings.outputs.build-output-dir }}" --target package --config ${{ matrix.build_type }}

    - name: Upload Artifact for Release on Windows
      if: ${{ matrix.os == 'windows-latest' }}
      uses: actions/upload-artifact@v4
      with:
        name: package-windows-${{ matrix.build_type }}-${{ matrix.cpp_compiler }}
        path: ${{ steps.strings.outputs.build-output-dir }}/EXANTE_Report_Analyzer-0.0.${{ github.run_number }}-win64.exe

    - name: Upload Artifact for Release on Linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: actions/upload-artifact@v4
      with:
        name: package-linux-${{ matrix.build_type }}-${{ matrix.cpp_compiler }}
        path: ${{ steps.strings.outputs.build-output-dir }}/EXANTE_Report_Analyzer-0.0.${{ github.run_number }}-Linux.tar.gz